from decouple import config

MONGODB_URI = config('MONGODB_URI')
MONGODB_DB = config("MONGODB_DB")
SECRET_KEY = config('SECRET_KEY')
ALGORITHM = config('ALGORITHM')
ACCESS_TOKEN_EXPIRE_MINUTES = config('ACCESS_TOKEN_EXPIRE_MINUTES')
CACHE_KEY_FORMAT = config('CACHE_KEY_FORMAT')
REDIS_MAX_CONNECTIONS = config('REDIS_MAX_CONNECTIONS')
REDIS_MIN_CONNECTIONS = config('REDIS_MIN_CONNECTIONS')
REDIS_HOST = config('REDIS_HOST')
REDIS_PORT = config('REDIS_PORT')
SERVICE_NAME = config('SERVICE_NAME')
